clone:
  depth: 1
kind: pipeline
name : Velvet Kernel
steps:
 - name: SM6250
   image: ghcr.io/sushrut1101/docker:arch
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - bash build.sh
